sudo: required
dist: trusty

env:
  global:
    - CONDA_DEPS="pip pytest numpy pandas scipy six scikit-learn"

matrix:
  include:
    - os: linux
      env:
         - PYTHON_VERSION=3.5
         - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
    - os: linux
      env:
         - PYTHON_VERSION=2.7
         - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh"

before_install:
- sudo apt-get -qq update

- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- wget $MINICONDA_URL -O miniconda.sh;
- bash miniconda.sh -b -f -p $MINICONDA;
- hash -r
- conda info -a

- conda config --set always_yes yes --set changeps1 no
- conda config --add channels conda-forge
- conda update -y conda
- rm -rf /home/travis/miniconda/envs/test-env
- conda create -q -n test-env python=$PYTHON_VERSION $CONDA_DEPS
- source activate test-env

install:
- pip install pytest coverage pytest-cov codecov
- pip install -r requirements.txt

before_script:
- python setup.py install

script:
- py.test --cov-report term-missing --cov=meica

after_success:
- codecov
- coveralls

before_cache:
# clean unused packages & installed files from conda cache
# this makes the cache rebuilt less frequently
# rm -rf /home/travis/miniconda/envs/test-env
- conda clean --tarballs --packages --index-cache
- rm -rf $HOME/miniconda/pkgs/cache

cache:
  directories:
    - $HOME/miniconda
